repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^src/pymeshup/DAVE/GHS_to_DAVE_form\.py$
      - id: trailing-whitespace
        exclude: ^src/pymeshup/DAVE/GHS_to_DAVE_form\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^src/pymeshup/DAVE/GHS_to_DAVE_form\.py$
      - id: ruff-format
        exclude: ^src/pymeshup/DAVE/GHS_to_DAVE_form\.py$

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx --no-install prettier --write
        language: system
        pass_filenames: true
        types_or: [javascript, jsx, ts, tsx, json, markdown, yaml, css, scss, html]
